/*
Makes use of no third-party code (for better or worse)

Copyright (c) 2014

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
(function(){var K,r=480,I=["hunger","health","sanity"],ta={hunger:!0,health:!0,sanity:!0},ua={bestHunger:!0,bestHealth:!0,bestSanity:!0},F=1*r,p=2*r,n=3*r,f=6*r,B=8*r,g=10*r,v=15*r,C=20*r,D=40*r,m=2*r,va=r/16*.6666,P={raw:1,dried:1,cooked:1,recipe:1},H=P,Y=[],E=39,A={vanilla:{name:"Vanilla",img:"vanilla.png",bit:1,mask:1,color:"#ff592e"},giants:{name:"Reign of Giants",img:"reign_of_giants.png",bit:2,mask:3,color:"#b857c6"},shipwrecked:{name:"Shipwrecked",img:"shipwrecked.png",bit:4,mask:7,color:"#50c1cc"},
hamlet:{name:"Hamlet",img:"hamlet.png",bit:32,mask:39,color:"#ffdf93"},together:{name:"Don't Starve Together",img:"together.png",bit:8,mask:11,color:"#c0c0c0"},warly:{name:"Warly",img:"warly.png",bit:16,mask:23,multipliers:{raw:.7,dried:.8,cooked:.9,recipe:1.2}}},Q=function(b){H={};for(c in P)P.hasOwnProperty(c)&&(H[c]=P[c]);E=b;for(var c=0;c<L.childNodes.length;c++){b=L.childNodes[c];var a=A[b.dataset.mode];b.className=0!==(E&a.bit)?"mode-button enabled":"mode-button";if(a.multipliers&&0!==(E&a.bit))for(var d in a.multipliers)a.multipliers.hasOwnProperty(d)&&
(H[d]*=a.multipliers[d])}for(c=0;c<Y.length;c++)Y[c]();d=["together","hamlet","shipwrecked","giants","vanilla"];for(c=0;c<d.length;c++)if(0!==(E&A[d[c]].bit)){document.getElementById("background").style["background-color"]=A[d[c]].color;break}},u={acorn:{name:"Birchnut",uncookable:!0,perish:C,stack:40,mode:"giants"},acorn_cooked:{name:"Roasted Birchnut",ideal:!0,seed:1,hunger:9.375,health:1,sanity:0,perish:f,stack:40,mode:"giants"},butter:{name:"Butter",fat:1,dairy:1,health:40,hunger:25,sanity:0,
perish:D,stack:40},butterflywings:{name:"Butterfly Wings",isveggie:!0,decoration:2,health:8,hunger:9.375,sanity:0,perish:f,stack:40},cactusflower:{name:"Cactus Flower",veggie:.5,hunger:12.5,health:8,sanity:5,perish:n,stack:40,mode:"giants"},deerclopseyeball:{name:"Deerclops Eyeball",uncookable:!0,health:60,hunger:75,sanity:-15},bird_egg:{name:"Egg",egg:1,health:0,hunger:9.375,sanity:0,perish:g,stack:40,rot:"rottenegg"},bird_egg_cooked:{name:"Cooked Egg",egg:1,precook:1,health:0,hunger:12.5,sanity:0,
perish:f,stack:40},rottenegg:{name:"Rotten Egg",uncookable:!0,health:-1,hunger:-10,sanity:0,stack:40},cutlichen:{name:"Lichen",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:-5,perish:p},eel:{name:"Eel",ismeat:!0,meat:.5,fish:1,health:3,hunger:9.375,sanity:0,perish:n,stack:40,dry:"morsel_dried",drytime:r},eel_cooked:{name:"Cooked Eel",ismeat:!0,health:8,hunger:12.5,sanity:0,perish:f,stack:40},fish:{name:"Fish",ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:n,stack:40,drytime:r,dry:"morsel_dried"},
fish_cooked:{name:"Cooked Fish",ismeat:!0,meat:.5,fish:1,precook:1,health:1,hunger:12.5,sanity:0,perish:f,stack:40},froglegs:{name:"Frog Legs",ismeat:!0,meat:.5,health:0,hunger:12.5,perish:f,sanity:-10,stack:40},froglegs_cooked:{name:"Cooked Frog Legs",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,perish:g,sanity:0,stack:40},goatmilk:{name:"Electric Milk",dairy:1,health:3,hunger:12.5,sanity:10,perish:f,stack:40,mode:"giants"},honey:{name:"Honey",sweetener:!0,health:3,hunger:9.375,sanity:0,perish:D,
stack:40},honeycomb:{name:"Honeycomb",sweetener:!0},ice:{name:"Ice",frozen:1,health:.5,hunger:2.34375,sanity:0,perish:n,stack:40,mode:"giants"},lightbulb:{name:"Light Bulb",health:1,hunger:0,sanity:0,perish:f,stack:40,uncookable:!0},mandrake:{name:"Mandrake",veggie:1,magic:1,health:60,hunger:75,sanity:0,stack:40},mandrake_cooked:{name:"Cooked Mandrake",uncookable:!0,veggie:1,magic:1,precook:1,health:100,hunger:150,sanity:0,stack:40},mole:{name:"Moleworm",ideal:!0,meat:.5,perish:2*r,cook:"morsel_cooked",
mode:"giants"},plantmeat:{name:"Leafy Meat",uncookable:!0,health:0,hunger:12.5,sanity:-10,perish:f,stack:40},plantmeat_cooked:{name:"Cooked Leafy Meat",uncookable:!0,health:1,hunger:18.75,sanity:0,perish:g,stack:40},monstermeat:{name:"Monster Meat",ismeat:!0,meat:1,monster:!0,health:-20,hunger:18.75,sanity:-15,perish:f,stack:20,dry:"monstermeat_dried",drytime:r},monstermeat_cooked:{name:"Cooked Monster Meat",ismeat:!0,meat:1,monster:!0,precook:1,health:-3,hunger:18.75,sanity:-10,perish:v,stack:20},
monstermeat_dried:{name:"Monster Jerky",ismeat:!0,meat:1,monster:!0,dried:1,health:-3,hunger:18.75,sanity:-5,perish:C,stack:20},meat:{name:"Meat",ismeat:!0,meat:1,health:1,hunger:25,sanity:-10,perish:f,stack:20,dry:"meat_dried",drytime:m},meat_cooked:{name:"Cooked Meat",ismeat:!0,meat:1,precook:1,health:3,hunger:25,sanity:0,perish:g,stack:20},meat_dried:{name:"Jerky",ismeat:!0,meat:1,dried:1,health:20,hunger:25,sanity:15,perish:C,stack:20},morsel:{name:"Morsel",ismeat:!0,meat:.5,health:0,hunger:12.5,
sanity:-10,perish:f,stack:40,drytime:r,dry:"morsel_dried"},morsel_cooked:{name:"Cooked Morsel",raw:"morsel",ismeat:!0,meat:.5,precook:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40},morsel_dried:{name:"Small Jerky",wet:"morsel",ismeat:!0,meat:.5,dried:1,health:8,hunger:12.5,sanity:10,perish:C,stack:40},drumstick:{name:"Drumstick",ismeat:!0,ideal:!0,meat:.5,health:0,hunger:12.5,sanity:-10,perish:f,stack:20,drytime:r,dry:"morsel_dried"},drumstick_cooked:{name:"Fried Drumstick",ismeat:!0,meat:.5,
precook:1,health:1,hunger:12.5,sanity:0,perish:g,stack:20},batwing:{name:"Batilisk Wing",ismeat:!0,health:3,hunger:12.5,sanity:-10,perish:f,stack:40,drytime:m,dry:"morsel_dried",uncookable:!0},batwing_cooked:{name:"Cooked Batilisk Wing",ismeat:!0,health:8,hunger:18.75,sanity:0,perish:g,uncookable:!0},minotaurhorn:{name:"Guardian's Horn",uncookable:!0,ismeat:!0,health:60,hunger:75,sanity:-15},red_mushroom:{name:"Red Cap",basename:"CapRed",veggie:.5,ideal:!0,health:-20,hunger:12.5,sanity:0,perish:g,
stack:40},red_mushroom_cooked:{name:"Cooked Red Cap",veggie:.5,health:1,hunger:0,sanity:-10,perish:g,stack:40},green_mushroom:{name:"Green Cap",basename:"CapGreen",veggie:.5,ideal:!0,health:0,hunger:12.5,sanity:-50,perish:g,stack:40},green_mushroom_cooked:{name:"Cooked Green Cap",veggie:.5,health:-1,hunger:0,sanity:15,perish:g,stack:40},blue_mushroom:{name:"Blue Cap",basename:"CapBlue",veggie:.5,ideal:!0,health:20,hunger:12.5,sanity:-15,perish:g,stack:40},blue_mushroom_cooked:{name:"Cooked Blue Cap",
veggie:.5,health:-3,hunger:0,sanity:10,perish:g,stack:40},petals:{name:"Petals",uncookable:!0,health:1,hunger:0,sanity:0,perish:f,stack:40},petals_evil:{name:"Dark Petals",basename:"Petals.",uncookable:!0,health:0,hunger:0,sanity:-5,perish:f,stack:40},seeds:{name:"Seeds",uncookable:!0,health:0,hunger:4.6875,sanity:0,perish:D,stack:40},seeds_cooked:{name:"Toasted Seeds",uncookable:!0,health:1,hunger:4.6875,sanity:0,perish:g,stack:40},spoiled_food:{name:"Rot",uncookable:!0,health:-1,hunger:-10,sanity:0,
stack:40},tallbirdegg:{name:"Tallbird Egg",egg:4,health:3,hunger:25,sanity:0},tallbirdegg_cooked:{name:"Fried Tallbird Egg",egg:4,precook:1,health:0,hunger:37.5,sanity:0,perish:f},trunk_summer:{name:"Koalefant Trunk",uncookable:!0,ismeat:!0,health:30,hunger:37.5,sanity:0,perish:f,stack:20},trunk_summer_cooked:{name:"Koalefant Trunk Steak",uncookable:!0,ismeat:!0,health:40,hunger:75,sanity:0,perish:v,stack:20},twigs:{name:"Twigs",inedible:1},cavebanana:{name:"Banana",ideal:!0,isfruit:!0,fruit:1,health:1,
hunger:12.5,sanity:0,perish:g},cavebanana_cooked:{name:"Cooked Banana",isfruit:!0,fruit:1,precook:1,health:3,hunger:12.5,sanity:0,perish:f},carrot:{name:"Carrot",isveggie:!0,veggie:1,health:1,hunger:12.5,perish:g,sanity:0,stack:40},carrot_cooked:{name:"Roasted Carrot",isveggie:!0,veggie:1,precook:1,health:3,hunger:12.5,perish:f,sanity:0,stack:40},corn:{name:"Corn",ideal:!0,isveggie:!0,veggie:1,health:3,hunger:25,perish:g,sanity:0,stack:40},corn_cooked:{name:"Popcorn",isveggie:!0,veggie:1,precook:1,
health:3,hunger:12.5,perish:v,sanity:0,stack:40},pumpkin:{name:"Pumpkin",isveggie:!0,veggie:1,health:3,hunger:37.5,perish:g,sanity:0,stack:20},pumpkin_cooked:{name:"Hot Pumpkin",isveggie:!0,veggie:1,precook:1,health:8,hunger:37.5,perish:f,sanity:0,stack:20},eggplant:{name:"Eggplant",isveggie:!0,veggie:1,health:8,hunger:25,perish:g,sanity:0,stack:20},eggplant_cooked:{name:"Braised Eggplant",isveggie:!0,veggie:1,precook:1,health:20,hunger:25,perish:f,sanity:0,stack:20},durian:{name:"Durian",isfruit:!0,
monster:1,fruit:1,health:-3,hunger:25,perish:g,sanity:-5,stack:20},durian_cooked:{name:"Extra Smelly Durian",isfruit:!0,monster:1,fruit:1,precook:1,health:0,hunger:25,perish:f,sanity:-5,stack:20},pomegranate:{name:"Pomegranate",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:f,sanity:0,stack:40},pomegranate_cooked:{name:"Sliced Pomegranate",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:n,sanity:0,stack:40},dragonfruit:{name:"Dragon Fruit",isfruit:!0,fruit:1,health:3,hunger:9.375,perish:f,
sanity:0,stack:40},dragonfruit_cooked:{name:"Prepared Dragon Fruit",isfruit:!0,fruit:1,precook:1,health:20,hunger:12.5,perish:n,sanity:0,stack:40},berries:{name:"Berries",isfruit:!0,fruit:.5,health:0,hunger:9.375,perish:f,sanity:0,stack:40},berries_cooked:{name:"Roasted Berries",isfruit:!0,fruit:.5,precook:1,health:1,hunger:12.5,perish:n,sanity:0,stack:40},cactusmeat:{name:"Cactus Flesh",ideal:!0,veggie:1,hunger:12.5,health:-3,perish:g,sanity:-5,stack:40,mode:"giants"},cactusmeat_cooked:{name:"Cooked Cactus Flesh",
veggie:1,hunger:12.5,health:1,perish:g,sanity:15,precook:1,stack:40,mode:"giants"},watermelon:{name:"Watermelon",fruit:1,ideal:!0,hunger:12.5,health:3,perish:f,sanity:5,stack:40,mode:"giants"},watermelon_cooked:{name:"Grilled Watermelon",fruit:1,hunger:12.5,health:1,perish:n,sanity:7.5,precook:1,stack:40,mode:"giants"},wormlight:{name:"Glow Berry",uncookable:!0,health:11,hunger:18.75,sanity:-10,perish:g,note:"Gives 90 seconds of light"},glommerfuel:{name:"Glommer's Goop",uncookable:!0,health:40,hunger:9.375,
sanity:-50,mode:"giants"},coral_brain:{name:"Brainy Matter",uncookable:!0,health:-10,hunger:10,sanity:50,perish:F,mode:"shipwrecked"},blubber:{name:"Blubber",uncookable:!0,health:10,hunger:10,sanity:0,perish:g,stack:10,mode:"shipwrecked"},seaweed:{name:"Seaweed",ideal:!0,veggie:1,health:1,hunger:9.375,sanity:-10,perish:f,stack:40,dry:"seaweed_dried",drytime:r,mode:"shipwrecked"},seaweed_cooked:{name:"Roasted Seaweed",veggie:1,health:3,hunger:9.375,sanity:0,perish:g,stack:40,mode:"shipwrecked"},seaweed_dried:{name:"Dried Seaweed",
veggie:1,health:3,hunger:12.5,sanity:0,perish:C,stack:40,mode:"shipwrecked"},sweet_potato:{name:"Sweet Potato",veggie:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},sweet_potato_cooked:{name:"Cooked Sweet Potato",veggie:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},coffeebeans:{name:"Coffee Beans",fruit:.5,health:0,hunger:9.375,sanity:0,perish:f,stack:40,mode:"shipwrecked"},coffeebeans_cooked:{name:"Roasted Coffee Beans",ideal:!0,fruit:1,health:0,hunger:9.375,
sanity:-5,perish:v,stack:40,note:"Gives 5 bonus speed (+83%) for 30 seconds",mode:"shipwrecked"},coconut_halved:{name:"Halved Coconut",basename:"Coconut.",fruit:1,fat:1,health:1,hunger:4.6875,sanity:0,perish:g,stack:40,cook:"coconut_cooked",mode:"shipwrecked"},coconut_cooked:{name:"Roasted Coconut",fruit:1,fat:1,health:1,hunger:9.375,sanity:0,perish:g,stack:40,mode:"shipwrecked"},doydoyegg:{name:"Doydoy Egg",egg:1,health:3,hunger:25,sanity:0,perish:g,mode:"shipwrecked"},doydoyegg_cooked:{name:"Fried Doydoy Egg",
egg:1,health:0,hunger:37.5,sanity:0,perish:f,mode:"shipwrecked"},tropical_fish:{name:"Tropical Fish",skip:!0,ismeat:!0,meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:n,stack:40,cook:"fish_raw_small_cooked",dry:"morsel_dried",drytime:r,mode:"shipwrecked"},fish_raw:{name:"Raw Fish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:n,stack:40,cook:"fish_med_cooked",dry:"meat_dried",drytime:r,mode:"shipwrecked"},fish_med:{name:"Dead Dogfish",meat:.5,fish:1,health:1,hunger:25,sanity:0,perish:f,stack:40,
rot:"spoiled_fish",dry:"meat_dried",drytime:r,mode:"shipwrecked"},dead_swordfish:{name:"Swordfish",uncookable:!0,health:1,hunger:25,sanity:0,perish:f,stack:40,cook:"fish_med_cooked",rot:"spoiled_fish",dry:"meat_dried",drytime:r,mode:"shipwrecked"},fish_med_cooked:{name:"Fish Steak",meat:.5,fish:1,health:20,hunger:25,sanity:0,perish:f,stack:40,mode:"shipwrecked"},shark_fin:{name:"Shark Fin",meat:.5,fish:1,health:20,hunger:25,sanity:-15,perish:f,stack:10,mode:"shipwrecked"},limpets:{name:"Limpets",
ideal:!0,fish:.5,health:0,hunger:12.5,sanity:-10,perish:f,stack:40,mode:"shipwrecked"},limpets_cooked:{name:"Cooked Limpets",fish:.5,health:1,hunger:12.5,sanity:0,perish:g,stack:40,mode:"shipwrecked"},mussel:{name:"Mussel",fish:.5,health:0,hunger:12.5,sanity:-10,perish:n,stack:40,mode:"shipwrecked"},mussel_cooked:{name:"Cooked Mussel",fish:.5,health:1,hunger:12.5,sanity:0,perish:n,stack:40,mode:"shipwrecked"},mysterymeat:{name:"Bile-Covered Slop",uncookable:!0,health:-1,hunger:-10,sanity:0,stack:20,
mode:"shipwrecked"},jellyfish:{name:"Jellyfish",fish:1,jellyfish:1,monster:1,perish:1.5*F,stack:40,mode:"shipwrecked"},jellyfish_dead:{name:"Dead Jellyfish",basename:"Jellyfish.",fish:1,jellyfish:1,monster:1,health:10,hunger:10,sanity:0,perish:f,stack:20,cook:"jellyfish_cooked",dry:"jellyfish_dried",drytime:r,mode:"shipwrecked"},jellyfish_cooked:{name:"Cooked Jellyfish",fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:g,stack:20,mode:"shipwrecked"},jellyfish_dried:{name:"Dried Jellyfish",
fish:1,jellyfish:1,monster:1,health:10,hunger:18.75,sanity:0,perish:C,stack:20,mode:"shipwrecked"},lobster:{name:"Wobster",fish:2,perish:2*r,mode:"shipwrecked"},lobster_dead:{name:"Dead Wobster",basename:"Wobster.",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:n,stack:10,cook:"lobster_cooked",mode:"shipwrecked"},lobster_cooked:{name:"Delicious Wobster",uncookable:!0,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},crab:{name:"Crab",skip:!0,fish:.5,perish:2*r,cook:"fish_raw_small_cooked",
mode:"shipwrecked"},fish_raw_small:{name:"Fish Morsel",fish:.5,health:1,hunger:12.5,perish:n,sanity:0,stack:40,dry:"morsel_dried",drytime:r,mode:"shipwrecked"},fish_raw_small_cooked:{name:"Cooked Fish Morsel",fish:.5,health:1,hunger:12.5,sanity:0,perish:f,stack:40,mode:"shipwrecked"},tigereye:{name:"Eye of the Tiger Shark",uncookable:!0,health:60,hunger:75,sanity:-15,stack:10,mode:"shipwrecked"},dragoonheart:{name:"Dragoon Heart",uncookable:!0,health:11,hunger:25,sanity:-10,perish:g,stack:10,note:"Gives 90 seconds of light",
mode:"shipwrecked"},roe:{name:"Roe",meat:.5,fish:1,health:1,hunger:4.6875,sanity:0,perish:n,stack:40,mode:"shipwrecked"},roe_cooked:{name:"Cooked Roe",meat:.5,fish:1,health:0,hunger:4.6875,sanity:0,perish:g,stack:40,mode:"shipwrecked"},fish3:{name:"Purple Grouper",meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40,note:"Gives 2 bonus speed (+33%) for 30 seconds",mode:"shipwrecked"},fish3_cooked:{name:"Cooked Purple Grouper",meat:.5,fish:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,
note:"Gives 2 bonus speed (+33%) for 30 seconds",mode:"shipwrecked"},fish4:{name:"Pierrot Fish",meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40,note:"Dries 1/s for 30 seconds",mode:"shipwrecked"},fish4_cooked:{name:"Cooked Pierrot Fish",meat:.5,fish:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,note:"Dries 1/s for 30 seconds",mode:"shipwrecked"},fish5:{name:"Neon Quattro",meat:.5,fish:1,health:1,hunger:12.5,sanity:0,perish:g,stack:40,note:"-3 heat",mode:"shipwrecked"},fish5_cooked:{name:"Cooked Neon Quattro",
meat:.5,fish:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,note:"-3 heat",mode:"shipwrecked"},asparagus:{name:"Asparagus",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,mode:"hamlet"},asparagus_cooked:{name:"Cooked Asparagus",isveggie:!0,veggie:1,health:3,hunger:25,sanity:0,perish:n,stack:40,mode:"hamlet"},radish:{name:"Radish",isveggie:!0,veggie:1,health:1,hunger:12.5,sanity:0,perish:v,stack:40,mode:"hamlet"},radish_cooked:{name:"Cooked Radish",isveggie:!0,veggie:1,health:3,
hunger:12.5,sanity:0,perish:g,stack:40,mode:"hamlet"},aloe:{name:"Aloe",isveggie:!0,veggie:1,health:8,hunger:9.375,sanity:0,perish:f,stack:40,mode:"hamlet"},aloe_cooked:{name:"Cooked Aloe",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:0,perish:n,stack:40,mode:"hamlet"},jellybug:{name:"Bean Bugs",bug:1,health:0,hunger:9.375,sanity:-10,perish:D,stack:40,mode:"hamlet"},jellybug_cooked:{name:"Cooked Bean Bugs",bug:1,health:1,hunger:12.5,sanity:-5,perish:g,stack:40,mode:"hamlet"},foliage:{name:"Foliage",
veggie:1,health:1,hunger:0,sanity:0,perish:f,stack:40,mode:"hamlet"},cutnettle:{name:"Nettle",antihistamine:1,health:0,hunger:0,sanity:0,note:"Prevents hayfever for 200 seconds",stack:40,mode:"hamlet"},snake_bone:{name:"Snake Bone",isbone:!0,bone:1,stack:20,mode:"hamlet"},piko_orange:{name:"Orange Piko",filter:1,perish:2*r,cook:"morsel_cooked",mode:"hamlet"},slugbug:{name:"Gummy Slug",bug:1,health:0,hunger:9.375,sanity:-10,perish:D,stack:40,mode:"hamlet"},slugbug_cooked:{name:"Cooked Gummy Slug",
bug:1,health:1,hunger:12.5,sanity:-5,perish:g,stack:40,mode:"hamlet"},weevole_carapace:{name:"Weevole Carapace",inedible:1,stack:40,mode:"hamlet"},clippings:{name:"Clippings",uncookable:!0,isveggie:!0,health:1,hunger:4.6875,sanity:0,stack:40,mode:"hamlet"},lotus_flower:{name:"Lotus Flower",uncookable:!0,isveggie:!0,health:1,hunger:12.5,sanity:5,perish:g,stack:40,mode:"hamlet"},lotus_flower_cooked:{name:"Cooked Lotus Root",uncookable:!0,isveggie:!0,health:1,hunger:12.5,sanity:15,perish:g,stack:40,
mode:"hamlet"},venus_stalk:{name:"Flytrap Stalk",uncookable:!0,health:0,hunger:12.5,sanity:-10,perish:f,stack:40,dry:"walkingstick",drytime:r,mode:"hamlet"},nectar_pod:{name:"Nectar",uncookable:!0,health:3,hunger:9.375,sanity:0,perish:D,stack:40,mode:"hamlet"},teatree_nut:{name:"Seed Pod",uncookable:!0,health:1,hunger:9.375,sanity:0,perish:C,stack:40,note:"Prevents hayfever for 60 seconds",mode:"hamlet"},teatree_nut_cooked:{name:"Cooked Seed Pod",uncookable:!0,health:3,hunger:9.375,sanity:0,perish:f,
stack:40,note:"Prevents hayfever for 120 seconds",mode:"hamlet"},tuber_crop:{name:"Tuber",uncookable:!0,isveggie:!0,health:0,hunger:12.5,sanity:0,perish:C,stack:10,note:"Poisonous",mode:"hamlet"},tuber_crop_cooked:{name:"Fried Tuber",uncookable:!0,health:3,hunger:18.75,sanity:0,perish:f,stack:10,note:"Poisonous",mode:"hamlet"},tuber_bloom_crop:{name:"Blooming Tuber",uncookable:!0,isveggie:!0,health:0,hunger:12.5,sanity:0,perish:C,stack:10,mode:"hamlet"},tuber_bloom_crop_cooked:{name:"Fried Blooming Tuber",
uncookable:!0,health:3,hunger:18.75,sanity:5,perish:f,stack:10,mode:"hamlet"},waterdrop:{name:"Magic Water",uncookable:!0,isveggie:!0,health:300,hunger:450,sanity:150,note:"Cures poison",mode:"hamlet"},wormlight_lesser:{name:"Lesser Glowberry",uncookable:!0,health:3,hunger:12.5,sanity:-10,perish:n,stack:40,note:"Gives 22.5 seconds of light",mode:"together"},phlegm:{name:"Phlegm",uncookable:!0,health:0,hunger:12.5,sanity:-15,perish:n,stack:40,mode:"together"},royal_jelly:{name:"Royal Jelly",sweetener:3,
health:40,hunger:12.5,sanity:15,perish:g,mode:"together"},kelp:{name:"Kelp Fronds",uncookable:!0,isveggie:!0,health:-1,hunger:9.375,sanity:-10,perish:g,stack:40,dry:"kelp_dried",drytime:.25*r,mode:"together"},kelp_cooked:{name:"Cooked Kelp Fronds",uncookable:!0,isveggie:!0,precook:1,health:0,hunger:9.375,sanity:-5,perish:g,stack:40,mode:"together"},kelp_dried:{name:"Dried Kelp Fronds",uncookable:!0,isveggie:!0,dried:1,health:1,hunger:9.375,sanity:10,perish:C,stack:40,mode:"together"},moonbutterflywings:{name:"Moon Moth Wings",
isveggie:!0,decoration:2,health:8,hunger:9.375,sanity:15,perish:f,stack:40,mode:"together"},moon_tree_blossom:{name:"Lune Tree Blossom",uncookable:!0,isveggie:!0,decoration:2,health:1,hunger:0,sanity:0,perish:f,stack:40,mode:"together"},rock_avocado_fruit_ripe:{name:"Ripe Stone Fruit",isveggie:!0,veggie:1,health:1,hunger:12.5,sanity:0,perish:n,stack:40,mode:"together"},rock_avocado_fruit_ripe_cooked:{name:"Cooked Stone Fruit",isveggie:!0,veggie:1,precook:1,health:3,hunger:12.5,sanity:0,perish:p,stack:40,
mode:"together"},pepper:{name:"Pepper",isveggie:!0,veggie:1,health:-20,hunger:9.375,sanity:-15,perish:v,stack:40,mode:"together"},pepper_cooked:{name:"Roasted Pepper",isveggie:!0,veggie:1,precook:1,health:-3,hunger:9.375,sanity:-10,perish:v,stack:40,mode:"together"},potato:{name:"Potato",isveggie:!0,veggie:1,health:-3,hunger:12.5,sanity:-5,perish:g,stack:40,mode:"together"},potato_cooked:{name:"Roasted Potato",isveggie:!0,veggie:1,precook:1,health:20,hunger:25,sanity:0,perish:f,stack:40,mode:"together"},
garlic:{name:"Garlic",isveggie:!0,veggie:1,health:0,hunger:9.375,sanity:-10,perish:v,stack:40,mode:"together"},garlic_cooked:{name:"Roasted Garlic",isveggie:!0,veggie:1,precook:1,health:1,hunger:9.375,sanity:-5,perish:g,stack:40,mode:"together"},tomato:{name:"Toma Root",isveggie:!0,veggie:1,health:3,hunger:12.5,sanity:0,perish:f,stack:40,mode:"together"},tomato_cooked:{name:"Roasted Toma Root",isveggie:!0,veggie:1,precook:1,health:20,hunger:12.5,sanity:0,perish:g,stack:40,mode:"together"},onion:{name:"Onion",
isveggie:!0,veggie:1,health:0,hunger:9.375,sanity:-10,perish:v,stack:40,mode:"together"},onion_cooked:{name:"Roasted Onion",isveggie:!0,veggie:1,precook:1,health:1,hunger:9.375,sanity:-5,perish:g,stack:40,mode:"together"},berries_juicy:{name:"Juicy Berries",isfruit:!0,fruit:.5,health:1,hunger:12.5,sanity:0,perish:p,stack:40,mode:"together"},berries_juicy_cooked:{name:"Roasted Juicy Berries",isfruit:!0,fruit:.5,precook:1,health:3,hunger:18.75,sanity:0,perish:F,stack:40,mode:"together"}},wa=function(){return this.op+
this.qty},xa={"=":function(b){return b===this.qty},">":function(b){return b>this.qty},"<":function(b){return b<this.qty},">=":function(b){return b>=this.qty},"<=":function(b){return b<=this.qty}},V={test:function(b){return!!b},toString:function(){return""}};p=function(b,c){return{op:b,qty:c,test:xa[b],toString:wa}};var ya=function(b,c,a){return this.item1.test(b,c,a)&&this.item2.test(b,c,a)},za=function(){return this.item1+" and "+this.item2},Aa=function(b,c,a){return this.item1.test(b,c,a)||this.item2.test(b,
c,a)},Ba=function(){return this.item1+" or "+this.item2};D=function(b,c){return{item1:b,item2:c,test:Aa,toString:Ba,cancel:b.cancel||c.cancel}};var Ca=function(b,c,a){return!this.item.test(b,c,a)},Da=function(){return this.item.toString().substring(0,this.item.toString().length-1)+"|strike]"};m=function(b){return{item:b,test:Ca,toString:Da,cancel:!0}};var Ea=function(b,c,a){return(c[this.name]||0)+(c[this.name+"_cooked"]||0)},Fa=function(){return"[*"+u[this.name].name+"|"+u[this.name].img+" "+u[this.name].name+
"]"+(u[this.name].cook?"[*"+u[this.name].cook.name+"|"+u[this.name].cook.img+"]":"")+(u[this.name].raw?"[*"+u[this.name].raw.name+"|"+u[this.name].raw.img+"]":"")+(this.qty?this.qty:"")},x=function(b,c){return{name:b,qty:c||V,test:Ea,toString:Fa}},Ga=function(b,c,a){return c[this.name]},Ha=function(){return"[*"+u[this.name].name+"|"+u[this.name].img+" "+u[this.name].name+"]"+(this.qty?this.qty:"")},q=function(b,c){return{name:b,qty:c||V,test:Ga,toString:Ha}},Ia=function(b,c,a){return a[this.tag]},
Ja=function(){return"[tag:"+this.tag+"|"+this.tag+"]"+(this.qty?this.qty:"")},e=function(b,c){return{tag:b,qty:c||V,test:Ia,toString:Ja}},k={butterflymuffin:{name:"Butter Muffin",test:function(b,c,a){return(c.butterflywings||c.moonbutterflywings)&&!a.meat&&a.veggie},requires:"Butterfly Wings, veggie",requirements:[D(x("butterflywings"),x("moonbutterflywings")),m(e("meat")),e("veggie")],priority:1,weight:1,foodtype:"veggie",health:20,hunger:37.5,perish:v,sanity:5,cooktime:2},frogglebunwich:{name:"Froggle Bunwich",
test:function(b,c,a){return(c.froglegs||c.froglegs_cooked)&&a.veggie},requirements:[x("froglegs"),e("veggie")],priority:1,foodtype:"meat",health:20,hunger:37.5,perish:v,sanity:5,cooktime:2},taffy:{name:"Taffy",test:function(b,c,a){return a.sweetener&&3<=a.sweetener&&!a.meat},requirements:[e("sweetener",p(">=",3)),m(e("meat"))],priority:10,foodtype:"veggie",health:-3,hunger:25,perish:v,sanity:15,cooktime:2,tags:["honeyed"]},pumpkincookie:{name:"Pumpkin Cookie",test:function(b,c,a){return(c.pumpkin||
c.pumpkin_cooked)&&a.sweetener&&2<=a.sweetener},requirements:[x("pumpkin"),e("sweetener",p(">=",2))],priority:10,foodtype:"veggie",health:0,hunger:37.5,perish:g,sanity:15,cooktime:2,tags:["honeyed"]},stuffedeggplant:{name:"Stuffed Eggplant",test:function(b,c,a){return(c.eggplant||c.eggplant_cooked)&&a.veggie&&1<a.veggie},requirements:[x("eggplant"),e("veggie",p(">",1))],priority:1,foodtype:"veggie",health:3,hunger:37.5,perish:v,sanity:5,temperature:40,temperatureduration:5,cooktime:2},fishsticks:{name:"Fishsticks",
test:function(b,c,a){return a.fish&&c.twigs&&a.inedible&&1>=a.inedible},requirements:[e("fish"),q("twigs"),e("inedible"),e("inedible",p("<=",1))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:g,sanity:5,cooktime:2},honeynuggets:{name:"Honey Nuggets",test:function(b,c,a){return c.honey&&a.meat&&1.5>=a.meat&&!a.inedible},requirements:[q("honey"),e("meat",p("<=",1.5)),m(e("inedible"))],priority:2,foodtype:"meat",health:20,hunger:37.5,perish:v,sanity:5,cooktime:2,tags:["honeyed"]},honeyham:{name:"Honey Ham",
test:function(b,c,a){return c.honey&&a.meat&&1.5<a.meat&&!a.inedible},requirements:[q("honey"),e("meat",p(">",1.5)),m(e("inedible"))],priority:2,foodtype:"meat",health:30,hunger:75,perish:v,sanity:5,temperature:40,temperatureduration:10,cooktime:2,tags:["honeyed"]},dragonpie:{name:"Dragonpie",test:function(b,c,a){return(c.dragonfruit||c.dragonfruit_cooked)&&!a.meat},requirements:[x("dragonfruit"),m(e("meat"))],priority:1,foodtype:"veggie",health:40,hunger:75,perish:v,sanity:5,temperature:40,temperatureduration:10,
cooktime:2},kabobs:{name:"Kabobs",test:function(b,c,a){return a.meat&&c.twigs&&(!a.monster||1>=a.monster)&&a.inedible&&1>=a.inedible},requirements:[e("meat"),q("twigs"),D(m(e("monster")),e("monster",p("<=",1))),e("inedible"),e("inedible",p("<=",1))],priority:5,foodtype:"meat",health:3,hunger:37.5,perish:v,sanity:5,cooktime:2},mandrakesoup:{name:"Mandrake Soup",test:function(b,c,a){return c.mandrake},requirements:[q("mandrake")],priority:10,foodtype:"veggie",health:100,hunger:150,perish:f,sanity:5,
cooktime:3},baconeggs:{name:"Bacon and Eggs",test:function(b,c,a){return a.egg&&1<a.egg&&a.meat&&1<a.meat&&!a.veggie},requirements:[e("egg",p(">",1)),e("meat",p(">",1)),m(e("veggie"))],priority:10,foodtype:"meat",health:20,hunger:75,perish:C,sanity:5,cooktime:2},meatballs:{name:"Meatballs",test:function(b,c,a){return a.meat&&!a.inedible},requirements:[e("meat"),m(e("inedible"))],priority:-1,foodtype:"meat",health:3,hunger:62.5,perish:g,sanity:5,cooktime:.75},bonestew:{name:"Meaty Stew",test:function(b,
c,a){return a.meat&&3<=a.meat&&!a.inedible},requirements:[e("meat",p(">=",3)),m(e("inedible"))],priority:0,foodtype:"meat",health:12,hunger:150,perish:g,sanity:5,temperature:40,temperatureduration:15,cooktime:.75},perogies:{name:"Pierogi",test:function(b,c,a){return a.egg&&a.meat&&a.veggie&&!a.inedible},requirements:[e("egg"),e("meat"),e("veggie"),m(e("inedible"))],priority:5,foodtype:"meat",health:40,hunger:37.5,perish:C,sanity:5,cooktime:1},turkeydinner:{name:"Turkey Dinner",test:function(b,c,a){return c.drumstick&&
1<c.drumstick&&a.meat&&1<a.meat&&(a.veggie||a.fruit)},requirements:[q("drumstick",p(">",1)),e("meat",p(">",1)),D(e("veggie"),e("fruit"))],priority:10,foodtype:"meat",health:20,hunger:75,perish:f,sanity:5,temperature:40,temperatureduration:10,cooktime:3},ratatouille:{name:"Ratatouille",test:function(b,c,a){return!a.meat&&a.veggie&&!a.inedible},requirements:[m(e("meat")),e("veggie"),m(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:25,perish:v,sanity:5,cooktime:1},jammypreserves:{name:"Fist Full of Jam",
test:function(b,c,a){return a.fruit&&!a.meat&&!a.veggie&&!a.inedible},requirements:[e("fruit"),m(e("meat")),m(e("veggie")),m(e("inedible"))],priority:0,foodtype:"veggie",health:3,hunger:37.5,perish:v,sanity:5,cooktime:.5},fruitmedley:{name:"Fruit Medley",test:function(b,c,a){return a.fruit&&3<=a.fruit&&!a.meat&&!a.veggie},requirements:[e("fruit",p(">=",3)),m(e("meat")),m(e("veggie"))],priority:0,foodtype:"veggie",health:20,hunger:25,perish:f,sanity:5,temperature:-40,temperatureduration:5,cooktime:.5},
fishtacos:{name:"Fish Tacos",test:function(b,c,a){return a.fish&&(c.corn||c.corn_cooked)},requirements:[e("fish"),x("corn")],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:f,sanity:5,cooktime:.5,tags:["monstermeat"]},waffles:{name:"Waffles",test:function(b,c,a){return c.butter&&(c.berries||c.berries_cooked||c.berries_juicy||c.berries_juicy_cooked)&&a.egg},requirements:[q("butter"),D(x("berries"),x("berries_juicy")),e("egg")],priority:10,foodtype:"veggie",health:60,hunger:37.5,perish:f,sanity:5,
cooktime:.5},monsterlasagna:{name:"Monster Lasagna",test:function(b,c,a){return a.monster&&2<=a.monster&&!a.inedible},requirements:[e("monster",p(">=",2)),m(e("inedible"))],priority:10,foodtype:"meat",health:-20,hunger:37.5,perish:f,sanity:-20,cooktime:.5},powcake:{name:"Powdercake",test:function(b,c,a){return c.twigs&&c.honey&&(c.corn||c.corn_cooked)},requirements:[q("twigs"),q("honey"),x("corn")],priority:10,foodtype:"veggie",health:-3,hunger:0,perish:9E6,sanity:0,cooktime:.5,tags:["honeyed"]},
unagi:{name:"Unagi",test:function(b,c,a){return c.cutlichen&&(c.eel||c.eel_cooked)},requirements:[q("cutlichen"),x("eel")],priority:20,foodtype:"veggie",health:20,hunger:18.75,perish:g,sanity:5,cooktime:.5},wetgoop:{name:"Wet Goop",test:function(b,c,a){return!0},requirements:[],trash:!0,priority:-2,health:0,hunger:0,perish:f,sanity:0,cooktime:.25},flowersalad:{name:"Flower Salad",test:function(b,c,a){return c.cactusflower&&a.veggie&&2<=a.veggie&&!a.meat&&!a.inedible&&!a.egg&&!a.sweetener&&!a.fruit},
requirements:[q("cactusflower"),e("veggie",p(">=",2)),m(e("meat")),m(e("inedible")),m(e("egg")),m(e("sweetener")),m(e("fruit"))],priority:10,foodtype:"veggie",health:40,hunger:12.5,perish:f,sanity:5,cooktime:.5,mode:"giants"},icecream:{name:"Ice Cream",test:function(b,c,a){return a.frozen&&a.dairy&&a.sweetener&&!a.meat&&!a.veggie&&!a.inedible&&!a.egg},requirements:[e("frozen"),e("dairy"),e("sweetener"),m(e("meat")),m(e("veggie")),m(e("inedible")),m(e("egg"))],priority:10,foodtype:"veggie",health:0,
hunger:25,perish:n,sanity:50,temperature:-40,temperatureduration:15,cooktime:.5,mode:"giants"},watermelonicle:{name:"Melonsicle",test:function(b,c,a){return c.watermelon&&a.frozen&&c.twigs&&!a.meat&&!a.veggie&&!a.egg},requirements:[q("watermelon"),e("frozen"),q("twigs"),m(e("meat")),m(e("veggie")),m(e("egg"))],priority:10,foodtype:"veggie",health:3,hunger:12.5,perish:n,sanity:20,temperature:-40,temperatureduration:10,cooktime:.5,mode:"giants"},trailmix:{name:"Trail Mix",test:function(b,c,a){return c.acorn_cooked&&
a.seed&&1<=a.seed&&(c.berries||c.berries_cooked||c.berries_juicy||c.berries_juicy_cooked)&&a.fruit&&1<=a.fruit&&!a.meat&&!a.veggie&&!a.egg&&!a.dairy},requirements:[q("acorn_cooked"),e("seed",p(">=",1)),D(x("berries"),x("berries_juicy")),e("fruit",p(">=",1)),m(e("meat")),m(e("veggie")),m(e("egg")),m(e("dairy"))],priority:10,foodtype:"veggie",health:30,hunger:12.5,perish:v,sanity:5,cooktime:.5,mode:"giants"},hotchili:{name:"Spicy Chili",test:function(b,c,a){return a.meat&&a.veggie&&1.5<=a.meat&&1.5<=
a.veggie},requirements:[e("meat",p(">=",1.5)),e("veggie",p(">=",1.5))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:0,temperature:40,temperatureduration:15,cooktime:.5,mode:"giants"},guacamole:{name:"Guacamole",test:function(b,c,a){return c.mole&&(c.rock_avocado_fruit_ripe||c.cactusmeat)&&!a.fruit},requirements:[q("mole"),D(q("cactusmeat"),q("rock_avocado_fruit_ripe")),m(e("fruit"))],priority:10,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:0,cooktime:.5,mode:"giants"},
californiaroll:{name:"California Roll",test:function(b,c,a){return c.seaweed&&2===c.seaweed&&a.fish&&1<=a.fish},requirements:[q("seaweed",p("=",2)),e("fish",p(">=",1))],priority:20,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:10,cooktime:.5,mode:"shipwrecked"},seafoodgumbo:{name:"Seafood Gumbo",test:function(b,c,a){return a.fish&&2<a.fish},requirements:[e("fish",p(">",2))],priority:10,foodtype:"meat",health:40,hunger:37.5,perish:g,sanity:20,cooktime:1,mode:"shipwrecked"},bisque:{name:"Bisque",
test:function(b,c,a){return c.limpets&&3===c.limpets&&a.frozen},requirements:[q("limpets",p("=",3)),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:18.75,perish:g,sanity:5,cooktime:1,mode:"shipwrecked"},ceviche:{name:"Ceviche",test:function(b,c,a){return a.fish&&2<=a.fish&&a.frozen},requirements:[e("fish",p(">=",2)),e("frozen")],priority:20,foodtype:"meat",health:20,hunger:25,perish:g,sanity:5,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},jellyopop:{name:"Jelly-O Pop",
test:function(b,c,a){return a.jellyfish&&a.frozen&&a.inedible},requirements:[e("jellyfish"),e("frozen"),e("inedible")],priority:20,foodtype:"meat",health:20,hunger:12.5,perish:n,sanity:0,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},bananapop:{name:"Banana Pop",test:function(b,c,a){return c.cavebanana&&a.frozen&&a.inedible&&!a.meat&&!a.fish},requirements:[q("cavebanana"),e("frozen"),e("inedible"),m(e("meat")),m(e("fish"))],priority:20,foodtype:"veggie",health:20,hunger:12.5,
perish:n,sanity:33,temperature:-40,temperatureduration:10,cooktime:.5,mode:"shipwrecked"},lobsterbisque:{name:"Lobster Bisque",test:function(b,c,a){return c.lobster&&a.frozen},requirements:[q("lobster"),e("frozen")],priority:30,foodtype:"meat",health:60,hunger:25,perish:g,sanity:10,cooktime:.5,mode:"shipwrecked"},lobsterdinner:{name:"Lobster Dinner",test:function(b,c,a){return c.lobster&&c.butter&&!a.meat&&!a.frozen},requirements:[q("lobster"),q("butter"),m(e("meat")),m(e("frozen"))],priority:25,
foodtype:"meat",health:60,hunger:37.5,perish:v,sanity:50,cooktime:1,mode:"shipwrecked"},sharkfinsoup:{name:"Shark Fin Soup",test:function(b,c,a){return c.shark_fin},requirements:[q("shark_fin")],priority:20,foodtype:"meat",health:40,hunger:12.5,perish:g,sanity:-10,cooktime:1,note:"Gives 10 naughtiness",mode:"shipwrecked"},surfnturf:{name:"Surf 'n' Turf",test:function(b,c,a){return a.meat&&2.5<=a.meat&&a.fish&&1.5<=a.fish&&!a.frozen},requirements:[e("meat",p(">=",2.5)),e("fish",p(">=",1.5)),m(e("frozen"))],
priority:30,foodtype:"meat",health:60,hunger:37.5,perish:g,sanity:33,cooktime:1,mode:"shipwrecked"},coffee:{name:"Coffee",test:function(b,c,a){return c.coffeebeans_cooked&&(4===c.coffeebeans_cooked||3===c.coffeebeans_cooked&&(a.dairy||a.sweetener))},requirements:[D(q("coffeebeans_cooked",p("=",4)),function(b,c){return{item1:b,item2:c,test:ya,toString:za,cancel:b.cancel&&c.cancel}}(q("coffeebeans_cooked",p("=",3)),D(e("dairy"),e("sweetener"))))],priority:30,foodtype:"veggie",health:3,hunger:9.375,
perish:g,sanity:-5,cooktime:.5,note:"Gives 5 bonus speed (+83%) for 240 seconds (0.5 days)",mode:"shipwrecked"},tropicalbouillabaisse:{name:"Tropical Bouillabaisse",test:function(b,c,a){return(c.fish3||c.fish3_cooked)&&(c.fish4||c.fish4_cooked)&&(c.fish5||c.fish5_cooked)&&a.veggie},requirements:[x("fish3"),x("fish4"),x("fish5"),e("veggie")],priority:35,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:15,cooktime:2,note:"Removes 3 heat, and for 30 seconds, dries 1/s and adds 2 bonus speed (+33%)",
mode:"shipwrecked"},caviar:{name:"Caviar",test:function(b,c,a){return(c.roe||3===c.roe_cooked)&&a.veggie&&1<=a.veggie},requirements:[D(q("roe"),q("roe_cooked",p("=",3))),e("veggie",p(">=",1))],priority:20,foodtype:"meat",health:3,hunger:12.5,perish:g,sanity:33,cooktime:2,mode:"shipwrecked"},sweetpotatosouffle:{name:"Sweet Potato Souffle",test:function(b,c,a){return c.sweet_potato&&2===c.sweet_potato&&a.egg&&2<=a.egg},requirements:[q("sweet_potato",p("=",2)),e("egg",p(">=",2))],priority:30,foodtype:"veggie",
health:20,hunger:37.5,perish:g,sanity:15,cooktime:2,mode:"warly"},monstertartare:{name:"Monster Tartare",test:function(b,c,a){return a.monster&&2<=a.monster&&a.egg&&a.veggie},requirements:[e("monster",p(">=",2)),e("egg"),e("veggie")],priority:30,foodtype:"meat",health:3,hunger:37.5,perish:g,sanity:10,cooktime:2,mode:"warly"},freshfruitcrepes:{name:"Fresh Fruit Crepes",test:function(b,c,a){return a.fruit&&1.5<=a.fruit&&c.butter&&c.honey},requirements:[e("fruit",p(">=",1.5)),q("butter"),q("honey")],
priority:30,foodtype:"veggie",health:60,hunger:150,perish:g,sanity:15,cooktime:2,mode:"warly"},musselbouillabaise:{name:"Mussel Bouillabaise",test:function(b,c,a){return c.mussel&&2===c.mussel&&a.veggie&&2<=a.veggie},requirements:[q("mussel",p("=",2)),e("veggie",p(">=",2))],priority:30,foodtype:"meat",health:20,hunger:37.5,perish:g,sanity:15,cooktime:2,mode:"warly"},nettlelosange:{name:"Nettle Rolls",test:function(b,c,a){return a.antihistamine&&3<=a.antihistamine},requirements:[e("antihistamine",
p(">=",3))],priority:0,foodtype:"veggie",health:20,hunger:25,perish:f,sanity:5,cooktime:.5,note:"Prevents hayfever for 720 seconds (1.5 days)",mode:"hamlet"},snakebonesoup:{name:"Snake Bone Soup",test:function(b,c,a){return a.bone&&2<=a.bone&&a.meat&&2<=a.meat},requirements:[e("bone",p(">=",2)),e("meat",p(">=",2))],priority:20,foodtype:"meat",health:40,hunger:25,perish:g,sanity:10,cooktime:1,mode:"hamlet"},tea:{name:"Tea",test:function(b,c,a){return a.filter&&2<=a.filter&&a.sweetener&&!a.meat&&!a.veggie&&
!a.inedible},requirements:[e("filter",p(">=",2)),e("sweetener"),m(e("meat")),m(e("veggie")),m(e("inedible"))],priority:25,foodtype:"veggie",health:3,hunger:12.5,perish:F,sanity:33,temperaturebump:15,cooktime:.5,rot:"icedtea",note:"Gives 2.5 bonus speed (+42%) for 120 seconds",mode:"hamlet"},icedtea:{name:"Iced Tea",test:function(b,c,a){return a.filter&&2<=a.filter&&a.sweetener&&a.frozen},requirements:[e("filter",p(">=",2)),e("sweetener"),e("frozen")],priority:30,foodtype:"veggie",health:3,hunger:12.5,
perish:f,sanity:33,temperaturebump:-10,cooktime:.5,note:"Gives 1.7 bonus speed (+28%) for 80 seconds",mode:"hamlet"},asparagussoup:{name:"Asparagus Soup",test:function(b,c,a){return(c.asparagus||c.asparagus_cooked)&&a.veggie&&1<a.veggie},requirements:[x("asparagus"),e("veggie",p(">",1))],priority:10,foodtype:"veggie",health:20,hunger:18.75,perish:v,sanity:5,cooktime:.5,mode:"hamlet"},spicyvegstinger:{name:"Spicy Vegetable Stinger",test:function(b,c,a){return(c.asparagus||c.asparagus_cooked||c.radish||
c.radish_cooked)&&a.veggie&&2<a.veggie&&a.frozen&&!a.meat},requirements:[D(x("asparagus"),x("radish")),e("veggie",p(">",2)),e("frozen"),m(e("meat"))],priority:15,foodtype:"veggie",health:3,hunger:25,perish:v,sanity:33,cooktime:.5,mode:"hamlet"},feijoada:{name:"Feijoada",test:function(b,c,a){return a.meat&&(3===c.jellybug||3===c.jellybug_cooked||3===c.jellybug+c.jellybug_cooked)},requirements:[e("meat"),x("jellybug",p("=",3))],priority:30,foodtype:"meat",health:20,hunger:75,perish:B,sanity:15,cooktime:3.5,
mode:"hamlet"},steamedhamsandwich:{name:"Steamed Ham Sandwich",test:function(b,c,a){return(c.meat||c.meat_cooked)&&a.veggie&&2<=a.veggie&&c.foliage},requirements:[x("meat"),e("veggie",p(">=",2)),q("foliage")],priority:5,foodtype:"meat",health:40,hunger:37.5,perish:f,sanity:15,cooktime:2,mode:"hamlet"},hardshell_tacos:{name:"Hard Shell Tacos",test:function(b,c,a){return 2==c.weevole_carapace&&a.veggie},requirements:[q("weevole_carapace",p("=",2)),e("veggie")],priority:1,foodtype:"veggie",health:20,
hunger:37.5,perish:v,sanity:5,cooktime:1,mode:"hamlet"},gummy_cake:{name:"Gummy Cake",test:function(b,c,a){return(c.slugbug||c.slugbug_cooked)&&a.sweetener},requirements:[x("slugbug"),e("sweetener")],priority:1,foodtype:"meat",health:3,hunger:150,perish:C,sanity:-5,cooktime:2,mode:"hamlet"},jellybean:{name:"Jellybeans",test:function(b,c,a){return c.royal_jelly&&!a.inedible&&!a.monster},requirements:[q("royal_jelly"),m(e("inedible")),m(e("monster"))],priority:12,foodtype:"goodies",health:2,hunger:0,
sanity:5,cooktime:2.5,note:"Recipe produces 3; heals 120 health over 2 minutes",mode:"together"},pepperpopper:{name:"Stuffed Pepper Poppers",test:function(b,c,a){return(c.pepper||c.pepper_cooked)&&a.meat&&1.5>=a.meat&&!a.inedible},requirements:[x("pepper"),e("meat",p("<=",1.5)),m(e("inedible"))],priority:20,foodtype:"meat",health:30,hunger:25,perish:v,sanity:-5,cooktime:2,temperature:40,temperatureduration:15,note:"Increases temperature by 40 degrees in 15 seconds.",mode:"together"},mashedpotatoes:{name:"Creamy Potato Pur\u00e9e",
test:function(b,c,a){return(2<=c.potato||2<=c.potato_cooked||2<=c.potato+c.potato_cooked)&&(c.garlic||c.garlic_cooked)&&!a.meat&&!a.inedible},requirements:[x("potato",p(">=",2)),x("garlic"),m(e("meat")),m(e("inedible"))],priority:20,foodtype:"veggie",health:20,hunger:37.5,perish:v,sanity:33,cooktime:1,mode:"together"},salsa:{name:"Salsa Fresca",test:function(b,c,a){return(c.tomato||c.tomato_cooked)&&(c.onion||c.onion_cooked)&&!a.meat&&!a.egg&&!a.inedible},requirements:[x("tomato"),x("onion"),m(e("meat")),
m(e("egg")),m(e("inedible"))],priority:20,foodtype:"veggie",health:30,hunger:25,perish:v,sanity:33,cooktime:.5,mode:"together"},potatotornado:{name:"Fancy Spiralled Tubers",test:function(b,c,a){return(c.potato||c.potato_cooked)&&a.inedible&&2>=a.inedible&&!a.meat&&(!a.monster||1>=a.monster)},requirements:[x("potato"),e("inedible",p("<=",2)),m(e("meat")),D(m(e("monster")),e("monster",p("<=",1)))],priority:10,foodtype:"veggie",health:3,hunger:37.5,perish:g,sanity:15,cooktime:.75,mode:"together"}},N=
function(){var b,c,a=/^tag[: ]/,d=/^tag:? */,e=/^tagnot[: ]/,f=/^tagnot:? */,t,g=/^recipe[: ]/,h=/^recipe:? */,m,p=/^ingredient[: ]/,n=/^ingredient:? */,la,ma,r=!1,q=function(a){!r&&a.uncookable||0===(a.modeMask&E)?a.match=0:0===a.lowerName.indexOf(b)||a.raw&&0===a.raw.lowerName.indexOf(b)?a.match=3:0===ma.test(a.lowerName)?a.match=2:la.test(a.lowerName)?a.match=1:a.match=0;return a.match},w=function(a){return a.match=a[c]+0||0},x=function(a){for(var b=0,c,d=!0;b<t.length;){c=t[b].test(null,a.nameObject,
a);if(t[b].cancel){if(!c){d=!0;break}}else c&&(d=!1);b++}return a.match=d?0:1},G=function(a){for(var b=0,c,d=!0;b<a.requirements.length;){c=a.requirements[b].test(null,m.nameObject,m);if(a.requirements[b].cancel){if(!c){d=!0;break}}else c&&(d=!1);b++}return a.match=d?0:1},Oa=function(a){return a.match=a.lowerName===b?1:0},Pa=function(a){return a.match=a.lowerName===b||a.raw&&a.raw.lowerName===b||a.cook&&a.cook.lowerName===b?1:0},v=function(a,b){if(a.match===b.match){var c=a.basename?a.basename:a.name;
var d=b.basename?b.basename:b.name;return c!==d?c>d?1:c<d?-1:0:a.name===b.name?0:a.raw===b?1:-1}return b.match-a.match};return function(l,y,Ka){r=!!Ka;b=y.toLowerCase();if(a.test(b))return c=b.split(d)[1],l.filter(w).sort(v);if(e.test(b))return c=b.split(f)[1],l.filter(function(a){return!w(a)}).sort(v);if(g.test(b))return(t=k.byName(b.split(h)[1].toLowerCase()))?(t=t.requirements,l.filter(x).sort(v)):[];if(p.test(b))return(m=u.byName(b.split(n)[1].toLowerCase()))?l.filter(G).sort(v):[];if(0===b.indexOf("*"))return b=
b.substring(1),l.filter(Oa).sort(v);if(0===b.indexOf("~"))return b=b.substring(1),l.filter(Pa).sort(v);ma=new RegExp("\\b"+b+".*");la=new RegExp("\\b"+b.split("").join(".*")+".*");return l.filter(q).sort(v)}}(),da=function(b,c,a){var d,e;for(d=0;d<b.length;d++){var f=b[d];if(null!==f)for(e in c[f.id]=1+(c[f.id]||0),f)if(f.hasOwnProperty(e)&&"perish"!==e&&!isNaN(f[e])){var t=f[e];ta[e]?t*=H[f.preparationType]:ua[e]&&(t*=H[f[e+"Type"]]);a[e]=t+(a[e]||0)}else"perish"===e&&(a[e]=Math.min(a[e]||C,f[e]))}},
na=function(){var b,c;return function(a,d,e,f){var l;a.length=0;b={};c={};da(d,b,c);c.hunger=c.bestHunger;c.health=c.bestHealth;c.sanity=c.bestSanity;d=0;a:for(;d<k.length;d++){var y=!1;if(0!==(k[d].modeMask&E)){for(l=0;l<k[d].requirements.length;l++)if(k[d].requirements[l].test(null,b,c))k[d].requirements[l].cancel||(y=!0);else if(!f&&k[d].requirements[l].cancel)continue a;else if(f&&!k[d].requirements[l].cancel)continue a;!y||e&&-1!==e.indexOf(k[d])||a.push(k[d])}}c.img="";c.name="Combined";return a}}(),
Qa=function(){var b=[],c,a;return function(d){b.length=0;c={};a={};da(d,c,a);a.hunger=a.bestHunger;a.health=a.bestHealth;a.sanity=a.bestSanity;for(d=0;d<k.length;d++)k[d].test(null,c,a)&&0!==(k[d].modeMask&E)&&b.push(k[d]);b.sort(function(a,b){return b.priority-a.priority});a.img="";a.name="Combined";a.priority=" ";a.perish=0;a.cooktime=0;b.unshift(a);return b}}(),M=function(){var b=document.createElement("canvas"),c=b.getContext&&b.toDataURL&&b.getContext("2d"),a=document.createElement("canvas"),
d=a.getContext&&a.getContext("2d"),e={},f={},t=!!c,g=[],k=function(l){var y=function(l,y){c.clearRect(0,0,64,64);c.drawImage(y,0,0,64,64);d.clearRect(0,0,32,32);d.drawImage(y,0,0,32,32);try{e[l]=b.toDataURL(),f[l]=a.toDataURL()}catch(Za){t=!1}g.filter(function(a){return a.url===l}).forEach(function(a){a.url===l&&(delete a.img.dataset.pending,R&&a.img.removeAttribute("data-pending"),a.img.src=32===a.d?f[l]||l:e[l]||l)});g=g.filter(function(a){return a.url!==l})};return function(a){y(l,a.target)}},
h=function(a,b,c){a.dataset.pending=b;R&&a.setAttribute("data-pending",b);g.push({url:b,img:a,d:c})},m=function(a,b){var c=new Image;if(t)if(e[a])c.src=32===b?f[a]:e[a];else{if(null!==e[a]){e[a]=null;var d=new Image;d.addEventListener("load",k(a),!1);d.src=a}h(c,a,b)}else c.src=a;return c};b.width=64;b.height=64;a.width=32;a.height=32;m.queue=h;return m}(),ea=function(){var b=/\[([^\|]*)\|([^\|\]]*)\|?([^\|\]]*)\]/,c=/([^\|]\]\[[^\|]+\|[^\|\]]+)\|?([^\|\](?:left)]*)(?=\])/g,a=/(\[[^\|]+\|[^\|\]]+)\|?([^\|\]]*)(?=\]\[)(?!\]\[\|)/g,
d=function(a,b,c){return b+"|"+(0===c.length?"left":c+" left")},e=function(a,b,c){return b+"|"+(0===c.length?"right":c+" right")},f=/_(\w)/g,g=function(a,b){return" "+b.toUpperCase()};return function(l){var y=l&&l.replace(c,d).replace(c,d).replace(a,e);l=y&&y.split(b);var t;if(l&&1!==l.length)for(y=document.createDocumentFragment(),y.appendChild(document.createTextNode(l[0])),t=1;t<l.length;t+=4){if(""===l[t]&&""===l[t+1])y.appendChild(document.createElement("br"));else{var k=document.createElement("span");
k.className=""===l[t+2]?"link":"link "+l[t+2];k.dataset.link=l[t];R&&k.setAttribute("data-link",l[t]);if(l[t+1]&&0===l[t+1].indexOf("img/")){k.appendChild(document.createTextNode(l[t+1].split(" ").slice(1).join(" ")));var h=l[t+1].split(" ")[0];var m=M(h,32);m.title=(h.substr(4,1).toUpperCase()+h.substr(5).replace(f,g)).split(".")[0];k.appendChild(m)}else k.appendChild(document.createTextNode(l[t+1]?l[t+1]:l[t]));y.appendChild(k)}y.appendChild(document.createTextNode(l[t+3]))}return y}}(),h;F=0;var oa=
document.getElementById("main"),Ra=document.getElementById("food"),Sa=document.getElementById("recipes"),fa=document.getElementById("navbar"),R=!1;document.documentElement.dataset||(R=!0,Object.defineProperty(Element.prototype,"dataset",{get:function(){this.ds||(this.ds={},Array.prototype.forEach.call(this.attributes,function(b){0===b.name.indexOf("data-")&&(this.ds[b.name.substring(5)]=b.value)},this));return this.ds}}));document.getElementById("stalehealth").appendChild(document.createTextNode("33.3%"));
document.getElementById("stalehunger").appendChild(document.createTextNode("66.7%"));document.getElementById("spoiledhunger").appendChild(document.createTextNode("50%"));document.getElementById("spoiledsanity").appendChild(document.createTextNode(10));document.getElementById("perishground").appendChild(document.createTextNode("150%"));document.getElementById("perishwinter").appendChild(document.createTextNode("75%"));document.getElementById("perishsummer").appendChild(document.createTextNode("125%"));
document.getElementById("perishfridge").appendChild(document.createTextNode("50%"));n=function(b,c){return"[tag:"+b+"|"+(c||b)+"]"};for(h in u)if(u.hasOwnProperty(h)){var d=u[h];d.match=0;d.lowerName=d.name.toLowerCase();d.id=h;d.nameObject={};d.nameObject[h]=1;d.img="img/"+d.name.replace(/ /g,"_").replace(/'/g,"").toLowerCase()+".png";d.preparationType=d.preparationType||"raw";u[h+"_cooked"]&&(d.cook=u[h+"_cooked"]);"string"===typeof d.cook&&(d.cook=u[d.cook]);d.cook&&!d.cook.raw&&(d.cook.raw=d,
d.cook.cooked=!0,d.cook.basename||(d.cook.basename=(d.basename||d.name)+"."));"string"===typeof d.raw&&(d.raw=u[d.raw],d.cooked=!0,d.basename||(d.basename=(d.raw.basename||d.raw.name)+"."));"string"===typeof d.dry&&(d.dry=u[d.dry]);d.dry&&!d.dry.wet&&(d.dry.wet=d,d.dry.rackdried=!0,d.dry.basename||(d.dry.basename=(d.basename||d.name)+".."));"string"===typeof d.wet&&(d.rackdried=!0,d.wet=u[d.wet],d.basename||(d.basename=(d.wet.basename||d.wet.name)+".."));d.cook&&(d.cook.preparationType="cooked");
d.dry&&(d.dry.preparationType="dried");for(h=0;h<I.length;h++)f=I[h],B=d[f]||0,g=d.preparationType,d.raw&&(B=Math.max(d.raw[f]||0,B),B===d.raw[f]&&(g="raw")),d.cook&&(B=Math.max(d.cook[f]||0,B),B===d.cook[f]&&(g="cooked")),f=f.charAt(0).toUpperCase()+f.slice(1),d["best"+f]=B,d["best"+f+"Type"]=g;d.info=[];f=d.info;d.fruit&&f.push(n("fruit")+(1===d.fruit?"":"\u00d7"+d.fruit));d.veggie&&f.push(n("veggie","vegetable")+(1===d.veggie?"":"\u00d7"+d.veggie));d.meat&&f.push(n("meat")+(1===d.meat?"":"\u00d7"+
d.meat));d.egg&&f.push(n("egg")+(1===d.egg?"":"\u00d7"+d.egg));d.fish&&f.push(n("fish")+(1===d.fish?"":"\u00d7"+d.fish));d.magic&&f.push(n("magic"));d.decoration&&f.push(n("decoration"));d.inedible&&f.push(n("inedible"));d.monster&&f.push(n("monster","monster food"));d.sweetener&&f.push(n("sweetener"));d.fat&&f.push(n("fat"));d.dairy&&f.push(n("dairy"));d.jellyfish&&f.push(n("jellyfish"));d.antihistamine&&f.push(n("antihistamine"));d.filter&&f.push(n("filter"));d.bug&&f.push(n("bug"));d.bone&&f.push(n("bone"));
d.comment&&f.push(d.comment);u[F++]=d}u.length=F;F=0;for(h in k)k.hasOwnProperty(h)&&(k[h].match=0,k[h].name=k[h].name||h,k[h].id=h,k[h].lowerName=k[h].name.toLowerCase(),k[h].weight=k[h].weight||1,k[h].priority=k[h].priority||0,k[h].img="img/"+k[h].name.replace(/ /g,"_").replace(/'/g,"").toLowerCase()+".png",k[h].requirements&&(k[h].requires=ea(k[h].requirements.join("; ")+(k[h].mode?"; [tag:"+k[h].mode+"|img/"+A[k[h].mode].img+"]":""))),k[h].mode?k[h][k[h].mode]=!0:(k[h].vanilla=!0,k[h].mode="vanilla"),
k[h].modeMask=A[k[h].mode].bit,k[h].temperature&&(k[h].note=k[h].note?k[h].note+"; ":"",k[h].note+="Provides "+k[h].temperature+" heat for "+k[h].temperatureduration+" seconds"),k[h].temperaturebump&&(k[h].note=k[h].note?k[h].note+"; ":"",k[h].note+=k[h].temperature+" heat when consumed"),k[h].preparationType="recipe",k[F++]=k[h]);k.length=F;k.forEach=Array.prototype.forEach;k.filter=Array.prototype.filter;k.sort=Array.prototype.sort;k.byName=function(b){for(var c=this.length;c--;)if(this[c].lowerName===
b)return this[c]};I=function(b,c){return b+"[recipe:"+c.name+"|"+c.img+"]"};var ha=function(b,c,a){return 1===c?b:b+(a||"s")};for(h=0;h<u.length;h++)d=u[h],f=d.info,d.cooked&&f.push("from [*"+d.raw.name+"|"+d.raw.img+"]"),d.cook&&(d.cook instanceof Object||(d.cook=u[d.cook]),f.push("cook: [*"+d.cook.name+"|"+d.cook.img+"]")),d.dry&&(d.dry instanceof Object||(d.dry=u[d.dry]),f.push("dry in "+d.drytime/r+" "+ha("day",d.drytime/r)+": [*"+d.dry.name+"|"+d.dry.img+"]")),d.mode?(d[d.mode]=!0,f.push("requires [tag:"+
d.mode+"|img/"+A[d.mode].img+"]")):(d.vanilla=!0,d.mode="vanilla"),d.modeMask=A[d.mode].bit,d.info=f.join("; "),d.uncookable?d.info+=(d.info?"[|]":"")+"cannot be added to crock pot":(d.recipes=[],k.forEach(function(b){for(var c=!1,a=b.requirements,e=a.length;e--;)if(a[e].test(null,d.nameObject,d))a[e].cancel||c||(c=!0);else if(a[e].cancel){c=!1;break}c&&d.recipes.push(b)}),0<d.recipes.length&&(d.ingredient=!0,d.info+=d.recipes.reduce(I,"[|][ingredient:"+d.name+"|Recipes] "))),d.note&&(d.info+="[|]"+
d.note),d.info=ea(d.info);u.forEach=Array.prototype.forEach;u.filter=Array.prototype.filter;u.sort=Array.prototype.sort;u.byName=function(b){for(var c=this.length;c--;)if(this[c].lowerName===b)return this[c]};var Ta=function(b,c,a){var d=a||[0,0,0,0],e,f=0,t=0;return function(a){for(var l;a--&&1<=b;){c(d);d[0]++;for(l=0;d[l]>=b;)l++,d[l]++;e=4;for(f=0;e--;)d[e]>=b?d[e]=f:d[e]>f&&(f=d[e]);if(4===l)return!1;t++}return!0}};var ia=K=void 0;K=k.filter(function(b){return!b.trash}).sort(function(b,c){return c.priority-
b.priority});ia=K.map(function(b){return b.test});K.map(function(b){return b.test.toString()});K.map(function(b){return b.priority});var Ua=function(b,c,a,d){var e=ia.length,f=[],l=0,g,k=60,h=function(a){return b[a]},m=Ta(b.length,function(a){a=a.map(h);var b,c=null,d={},l={},t=null,g=!1,k=ia,y=K;da(a,d,l);l.hunger=l.bestHunger;l.health=l.bestHealth;l.sanity=l.bestSanity;for(b=0;b<e&&(null===c||y[b].priority>=c);b++)k[b](null,d,l)&&(null!==t&&(g=!0,t.multiple=!0),t={recipe:y[b],ingredients:a,tags:{health:l.health,
hunger:l.hunger},multiple:g},f.push(t),c=y[b].priority)}),p=function(){var b=!1,e=Date.now();for(m(k)?setTimeout(p,0):b=!0;l<f.length&&f[l];l++)c(f[l]);g!==Date.now()-e&&(g=Date.now()-e+1,k=38/g*k+1|0);a&&a();b&&d&&d()};p()},S;(function(){var b=fa.getElementsByTagName("li"),c={},a={},d=function(a){S(a.target.dataset.tab)};S=function(b){f.className="";f=c[b];t.style.display="none";t=a[b];f.className="selected";t.style.display="block"};for(h=0;h<b.length;h++){var e=b[h];e.dataset.tab&&(c[e.dataset.tab]=
e,a[e.dataset.tab]=document.getElementById(e.dataset.tab),a[e.dataset.tab].style.display="none",e.addEventListener("selectstart",function(a){a.preventDefault()},!1),e.addEventListener("click",d,!1))}var f=c.simulator;var t=a.simulator;try{if(window.localStorage&&localStorage.foodGuideState){var g=JSON.parse(localStorage.foodGuideState);g.activeTab&&c[g.activeTab]&&(f=c[g.activeTab],t=a[g.activeTab],E=g.modeMask||A.shipwrecked.mask)}}catch(La){console&&console.warn("Unable to access localStorage",
La)}f.className="selected";t.style.display="block";window.addEventListener("beforeunload",function(){try{if(window.localStorage){localStorage.foodGuideState||(localStorage.foodGuideState="{}");var a=JSON.parse(localStorage.foodGuideState);a.activeTab=f.dataset.tab;a.modeMask=E;localStorage.foodGuideState=JSON.stringify(a)}}catch(Ma){console&&console.warn("Unable to access localStorage",Ma)}})})();var Va=function(b){b.dataset.pending&&M.queue(b,b.dataset.pending,32)},ja=function(b){var c,a,d=document.createElement("tr");
for(c=1;c<arguments.length;c++){var e=document.createElement(b);var f=(a=arguments[c])&&a.indexOf?a:a.toString();a instanceof DocumentFragment?(e.appendChild(a.cloneNode(!0)),Array.prototype.forEach.call(e.getElementsByTagName("img"),Va)):0===f.indexOf("img/")?(a=M(f),e.appendChild(a)):a&&a.nodeType&&1===a.nodeType?e.appendChild(a):e.appendChild(document.createTextNode(f));d.appendChild(e)}return d},pa=function(b){if(b&&"Combined"===b)return b;var c=document.createElement("a");c.setAttribute("target",
"_blank");c.setAttribute("href","http://dontstarve.wikia.com/wiki/"+b.replace(/\s/g,"_"));b=document.createTextNode(b);c.appendChild(b);return c},T=function(b,c,a,d,e,f,g,k,h,m){var l,t,y,p=!1,n,u,w,r=function(b,c,d){m&&!(w<m)||k&&!k(b)||(c=a(b),g&&g(b,d)&&(c.className="highlighted",n||(n=c),u=c),l.appendChild(c),w++)},q=function(a,d,g){var k;if(d||a&&""!==a.target.dataset.sort||y){var h=d||a&&a.target.dataset.sort||y;e&&(k=c.shift());"name"===h?c.sort(function(a,b){var c=a.basename?a.basename:a.name,
d=b.basename?b.basename:b.name;return c!==d?c>d?1:c<d?-1:0:a.name===b.name?0:a.raw===b?1:-1}):c.sort(function(a,b){var c=a[h],d=b[h];return isNaN(c)||isNaN(d)?isNaN(c)&&isNaN(d)?0:isNaN(c)?1:-1:d-c});if(d||a)y===h?p=!p:(y=h,p=!1);p&&c.reverse();e&&c.unshift(k)}a=document.createElement("tr");for(t in b)d=document.createElement("th"),-1===t.indexOf(":")?d.appendChild(document.createTextNode(t)):(d.appendChild(document.createTextNode(t.split(":")[0])),d.title=t.split(":")[1]),b[t]&&(b[t]===y&&(d.style.background=
p?"#555":"#ccc",d.style.color=p?"#ccc":"#555",d.style.borderRadius="4px"),d.style.cursor="pointer",d.dataset.sort=b[t],d.addEventListener("click",q,!1)),a.appendChild(d);d=l;l=document.createElement("table");l.appendChild(a);u=n=null;w=0;c.forEach(r);f&&(l.className="links",Array.prototype.forEach.call(l.getElementsByClassName("link"),function(a){a.addEventListener("click",f,!1)}));d&&d.parentNode.replaceChild(l,d);g&&(n&&n.offsetTop+l.offsetTop+oa.offsetTop+n.offsetHeight>window.scrollY+window.innerHeight?
n.scrollIntoView(!0):u&&u.offsetTop+l.offsetTop+oa.offsetTop<window.scrollY&&u.scrollIntoView(!1))};d?q(null,d):q();l.update=function(a){q(null,null,a)};l.setMaxRows=function(a){m=a;this.update()};return l},z=function(b){if(isNaN(b))return"";b=parseFloat(parseFloat(b).toFixed(4));return 0<b?"+"+b:b},qa=function(b,c){return b<c?(c-b)/Math.abs(b):b>c?-(b-c)/Math.abs(b):0},ka=function(b,c){var a=isNaN(b)||b===c?"":" ("+z((100*(b<c?(c-b)/Math.abs(b):b>c?-(b-c)/Math.abs(b):0)).toFixed(0))+"%)";return-1===
a.indexOf("Infinity")?a:" ("+z(c-b)+")"},ra=function(b){var c=H[b.preparationType],a=z(b.health*c),d=z(b.hunger*c);c=isNaN(b.sanity)?"":b.sanity*c;if(b.cook){var e=H[b.cook.preparationType];b.cook.health!==(b.health||0)&&(a+=" ("+z(b.cook.health*e-(a||0))+")");b.cook.hunger!==(b.hunger||0)&&(d+=" ("+z(b.cook.hunger*e-(d||0))+")");b.cook.sanity!==(b.sanity||0)&&(c+=" ("+z(b.cook.sanity*e-(c||0))+")")}return ja("td",b.img?b.img:"",pa(b.name),a,d,c,isNaN(b.perish)?"Never":b.perish/r+" "+ha("day",b.perish/
r),b.info||"")},aa=function(b,c,a,d){var e=H[b.preparationType]||1,f=b.health*e,l=b.hunger*e;e*=b.sanity;return ja("td",b.img?b.img:"",pa(b.name),z(f)+ka(c,f),z(l)+ka(a,l),isNaN(e)?"":z(e)+ka(d,e),isNaN(b.perish)?"Never":b.perish/r+" "+ha("day",b.perish/r),(b.cooktime*va+.5|0)+" secs",b.priority||"0",b.requires||"",b.note||"")};(function(){var b,c=[],a=[],d=function(a){return 0!==(a.modeMask&E)},e=T({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
Info:""},Array.prototype.slice.call(u),ra,"name",!1,function(d){d=d.target?"IMG"===d.target.tagName?d.target.parentNode.dataset.link:d.target.dataset.link:d;"recipe:"===d.substring(0,7)||"ingredient:"===d.substring(0,11)?(S("crockpot"),"recipe:"===d.substring(0,7)&&(d="*"+d.substring(7)),a=N(k,d),f.update(!0)):(b!==d?(b=d,c=N(u,d)):(b="",c.length=0),e.update(!0))},function(a){return-1!==c.indexOf(a)},d),f=T({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
"Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},Array.prototype.slice.call(k),aa,"name",!1,function(d){d=d.target?"IMG"===d.target.tagName?d.target.parentNode.dataset.link:d.target.dataset.link:d;var l=d.substring(d.indexOf(":")+1);A[l]?(a=N(k,d),f.update(!0)):(S("foodlist"),b=d,c=N(u,d),e.update(!0))},function(b){return-1!==a.indexOf(b)},d);Ra.appendChild(e);Sa.appendChild(f);
Y.push(function(){e.update();f.update()})})();var Wa=function(b,c){return b+"[ingredient:"+u[c.id].name+"|"+u[c.id].img+"]"},sa=function(b){var c=document.createElement("button");c.appendChild(document.createTextNode("Calculate efficient recipes (may take some time)"));c.className="makablebutton";c.addEventListener("click",function(){var a=[],d=b?b.length:null,e,f,g=[],h=[],m=[],p=function(a){return-1!==m.indexOf(a.id)},n=function(a){return-1!==this.indexOf(u[a])},q=function(a){-1!==m.indexOf(a.target.dataset.id)&&
m.splice(m.indexOf(a.target.dataset.id),1);-1!==h.indexOf(a.target.dataset.id)?(h.splice(h.indexOf(a.target.dataset.id),1),a.target.className=""):(h.push(a.target.dataset.id),a.target.className="selected");G.update()},r=function(a){-1!==h.indexOf(a.target.dataset.id)&&h.splice(h.indexOf(a.target.dataset.id),1);-1!==m.indexOf(a.target.dataset.id)?(m.splice(m.indexOf(a.target.dataset.id),1),a.target.className=""):(m.push(a.target.dataset.id),a.target.className="excluded");G.update();a.preventDefault()},
v=[],x=[],D=function(a){f&&(f.className="");for(var b=0;b<x.length;b++)x[b].className="";v.length=0;x.length=0;e===a.target.dataset.recipe?e=f=null:(e=a.target.dataset.recipe,f=a.target,a.target.className="selected");G.update()},w=function(a){f&&(f.className="",e=f=null);var b=x.indexOf(a.target);-1!==b?(v.splice(b,1),x.splice(b,1),a.target.className=""):(v.push(a.target.dataset.recipe),x.push(a.target),a.target.className="excluded");G.update();a.preventDefault()};null===d&&(d=u.length,b=u);for(;d--;)b[d].skip?
!b[d].cook||b[d].cook.uncookable||b[d].cook.skip||-1!==a.indexOf(b[d].cook)?!b[d].dry||b[d].dry.uncookable||b[d].dry.skip||-1!==a.indexOf(b[d].dry)||a.push(b[d].dry):a.push(b[d].cook):b[d].uncookable||b[d].cooked&&!b[d].ideal||b[d].rackdried&&!b[d].ideal||-1!==a.indexOf(b[d])||a.push(b[d]),!b[d].cooked||b[d].raw.uncookable||b[d].raw.skip||-1!==a.indexOf(b[d].raw)||a.push(b[d].raw),!b[d].rackdried||b[d].wet.uncookable||b[d].wet.skip||-1!==a.indexOf(b[d].wet)||a.push(b[d].wet);var C=[];var G=T({"":"",
Name:"name",Health:"health","Health+:Health gained compared to ingredients":"healthpls",Hunger:"hunger","Hunger+:Hunger gained compared to ingredients":"hungerpls",Ingredients:""},C,function(a){var b=a.recipe;return ja("td",b.img?b.img:"",b.name,z(b.health),z(a.healthpls)+" ("+z(100*a.healthpct|0)+"%)",z(b.hunger),z(a.hungerpls)+" ("+z(100*a.hungerpct|0)+"%)",ea(a.ingredients.reduce(Wa,"")+(a.multiple?"*":"")))},"hungerpls",!1,null,null,function(a){return(!e||a.recipe.name===e)&&(0===v.length||-1===
v.indexOf(a.recipe.name))&&(!m.length||!a.ingredients.some(p))&&(!h.length||h.every(n,a.ingredients))},0,15);var A=document.createElement("div");var F=document.createElement("div");F.appendChild(document.createTextNode("Computing combinations.."));d=document.createElement("div");d.appendChild(document.createTextNode("* combination has multiple possible results"));A.appendChild(F);var E=document.createElement("div");E.className="recipeFilter";A.appendChild(E);var ca=document.createElement("div");ca.className=
"foodFilter";a.forEach(function(a){var b=M(a.img,32);b.dataset.id=a.id;b.addEventListener("click",q,!1);b.addEventListener("contextmenu",r,!1);b.title=a.name;ca.appendChild(b)});A.appendChild(ca);var Na=document.createElement("div");var B=document.createElement("input");B.type="text";B.placeholder="use custom filter";B.className="customFilterInput";Na.appendChild(B);A.appendChild(G);c.parentNode.replaceChild(A,c);A.appendChild(d);Ua(a,function(a){var b;if(-1===g.indexOf(a.recipe.name)){for(b=0;b<
g.length&&!(a.recipe.name<g[b]);b++);g.splice(b,0,a.recipe.name);var c=M(k.byName(g[b].toLowerCase()).img);c.dataset.recipe=g[b];c.addEventListener("click",D,!1);c.addEventListener("contextmenu",w,!1);c.title=a.recipe.name;b<E.childNodes.length?E.insertBefore(c,E.childNodes[b]):E.appendChild(c)}a.name||(a.name=a.recipe.name,a.health=a.recipe.health,a.ihealth=a.tags.health,a.healthpls=a.recipe.health-a.ihealth,a.hunger=a.recipe.hunger,a.ihunger=a.tags.hunger,a.hungerpls=a.recipe.hunger-a.ihunger,a.healthpct=
qa(a.ihealth,a.recipe.health),a.hungerpct=qa(a.ihunger,a.recipe.hunger),a.sanity=a.recipe.sanity,a.perish=a.recipe.perish);C.push(a)},function(){F.firstChild.textContent="Found "+C.length+" valid recipes.. (you can change Food Guide tabs during this process)"},function(){G.setMaxRows(30);F.firstChild.textContent="Found "+C.length+" valid recipes. Showing top 30 for selected recipe using all selected ingredients. Right-click to exclude recipes or ingredients."})},!1);return c};document.getElementById("statistics").appendChild(sa());
var Xa=function(b,c){return b.reduce(function(a,b){return Math.max(a,b[c]||0)},-1E5)};window.food=u;window.recipes=k;window.matchingNames=N;var W=function(b,c){if(null!==c)b.dataset.id=c.id;else{if(b.nextSibling&&null!==O(b.nextSibling)){W(b,O(b.nextSibling));W(b.nextSibling,null);return}b.dataset.id=null}null!==c?b.firstChild?b.replaceChild(M(c.img),b.firstChild):b.appendChild(M(c.img)):b.firstChild&&b.removeChild(b.firstChild);b.title=c?c.name:""},O=function(b){return b&&(u[b.dataset.id]||k[b.dataset.id]||
null)};(function(){for(var b=document.getElementsByClassName("ingredientpicker"),c=b.length;c--;)(function(){var a=document.createElement("span"),d=document.createElement("div"),e=document.createElement("ul"),f=b[c],g=c,h,m="recipes"===f.dataset.type?k:u,p=!f.dataset.cookable,n=f.nextSibling,q=n.getElementsByClassName("ingredient"),r=[],v,x=[],A=[],w=null,D=!1,G=document.getElementById("results"),C=document.getElementById("discoverfood"),E=document.getElementById("discover"),F=document.getElementById("makable"),
z=document.createElement("span"),B=document.createElement("span"),H=function(a,b){for(var c=a;c.previousSibling;)if(c=c.previousSibling,b(c))return c;return null},K=function(a,b){for(var c=a;c.nextSibling;)if(c=c.nextSibling,b(c))return c;return null},I=!1,L=function(a){var b=u[a]||k[a]||null;if(!a)return console&&console.warn("ID not set"),-1;if(ba){for(a=0;a<q.length;a++)if(null===O(q[a]))return W(q[a],b),D&&v(),a;return-1}-1===q.indexOf(a)&&(q.push(a),a=document.createElement("span"),a.className=
"ingredient",W(a,b),a.addEventListener("click",Q,!1),n.appendChild(a),D&&v());return 1},P=function(a){-1!==L((a.target.dataset.id?a.target:a.target.parentNode).dataset.id)&&a&&a.preventDefault&&a.preventDefault()},R=function(a){var b=M(a.img,32),c=document.createElement("span");c.classList.add("item");c.appendChild(b);U=document.createElement("span");U.classList.add("text");U.appendChild(document.createTextNode(a.name));c.appendChild(U);c.dataset.id=a.id;-1!==r.indexOf(a)&&(c.style.opacity=.5);c.addEventListener("mousedown",
P,!1);this.appendChild(c);this.dataset.length++},S=function(a){-1!==r.indexOf(u[a.dataset.id])?a.style.opacity||(a.style.opacity=.5):a.style.opacity&&a.style.removeProperty("opacity")},Q=function(a){var b="IMG"===a.target.tagName?a.target.parentNode:a.target;if(ba){if(null!==O(b))return W(b,null),v(),b.dataset.id}else return a=q.indexOf(b.dataset.id),q.splice(a,1),n.removeChild(b),v(),q[a]||null},Z=function(){X.splitTag();var a=N(m,X.getSearch(),p);d.removeChild(e);e=document.createElement("div");
e.dataset.length=0;a.forEach(R,e);d.appendChild(e);w=null},V=function(a){a="IMG"===a.target.tagName?a.target.parentNode.dataset.link:a.target.dataset.link;var b=N(m,a,p);1===b.length?L(b[0].id):(f.value=a,Z())},J;"ingredients"===n.id?v=function(){r=Array.prototype.map.call(q,function(a){return O(a)});var a=Qa(r);var b=a[0].health;var c=a[0].hunger;var d=a[0].sanity;var f=T({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime",
"Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},a,function(a){return aa(a,b,c,d)},"priority",!0,V,function(a,b){return 0<b.length&&a.priority===Xa(b,"priority")});G.firstChild&&G.removeChild(G.firstChild);G.firstChild&&(G.removeChild(G.firstChild),G.removeChild(G.firstChild));G.appendChild(f);null!==r[0]&&(na(x,r,a),0<x.length&&(G.appendChild(document.createTextNode("Add more ingredients to make:")),
f=T({"":"",Name:"name","Health:(% more than ingredients)":"health","Hunger:(% more than ingredients)":"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish","Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},x,function(a){return aa(a,b,c,d)},"priority",!1,V),G.appendChild(f)));e&&e.firstChild&&Array.prototype.forEach.call(e.getElementsByTagName("span"),S)}:"inventory"===n.id&&
(v=function(){r=Array.prototype.map.call(n.getElementsByClassName("ingredient"),function(a){return O(a)});C.firstChild&&C.removeChild(C.firstChild);E.firstChild&&E.removeChild(E.firstChild);F.firstChild&&F.removeChild(F.firstChild);if(0<r.length){var a=T({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",Info:""},r,ra,"name");C.appendChild(a);na(A,r,null,!0);0<A.length&&(a=T({"":"",Name:"name",Health:"health",Hunger:"hunger",Sanity:"sanity","Perish:Time to turn to rot":"perish",
"Cook Time":"cooktime","Priority:One of the highest priority recipes for a combination will be made":"priority","Requires:Dim, struck items cannot be used":"",Notes:""},A,aa,"name"),E.appendChild(a),F.appendChild(sa(r)))}e&&e.firstChild&&Array.prototype.forEach.call(e.getElementsByTagName("span"),S)});if(0!==q.length){var ba=!0;Array.prototype.forEach.call(q,function(a){W(a,null);a.addEventListener("click",Q,!1)})}else q=[],ba=!1;try{window.localStorage&&localStorage.foodGuideState&&(h=JSON.parse(localStorage.foodGuideState).pickers)&&
h[g]&&h[g].forEach(function(a){u[a]&&L(a)})}catch(Ya){console&&console.warn("Unable to access localStorage",Ya)}D=!0;a.className="searchselector retracted";a.appendChild(document.createTextNode("name"));var X=function(){var b=document.createElement("div"),c=!1,d=null,e=[{title:"name",prefix:"",placeholder:"Filter ingredients"},{title:"tag",prefix:"tag:",placeholder:"Meat, veggie, fruit, egg, monster..."},{title:"recipe",prefix:"recipe:",placeholder:"Find ingredients used in a recipe"}],g=e[0],h=null,
k=function(){c=!1;b.style.height="0px";a.style.borderBottomLeftRadius="3px";b.style.borderTopLeftRadius="3px";null!==h&&(clearTimeout(h),h=null);a.className="searchselector retracted"},l=function(b){g=b;f.placeholder=g.placeholder;a.firstChild.textContent=g.title},m=function(a){l(e[a.target.dataset.typeIndex]);Z();k()},n=/: */;a.addEventListener("click",function(){c?k():(null===d&&(b.style.height="auto",b.style.left=a.offsetLeft,b.style.top=a.offsetTop+a.offsetHeight,d=b.offsetHeight+"px",b.style.height=
"0px"),c=!0,b.style.height=d,a.style.borderBottomLeftRadius="0px",b.style.borderTopLeftRadius="0px",b.style.width="auto",b.style.width=Math.max(b.offsetWidth,a.offsetWidth+1)+"px",null!==h&&(clearTimeout(h),h=null),a.className="searchselector extended")},!1);a.addEventListener("selectstart",function(a){a.preventDefault()},!1);a.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);a.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);
b.addEventListener("mouseout",function(){null!==h&&clearTimeout(h);h=setTimeout(k,500)},!1);b.addEventListener("mouseover",function(){null!==h&&(clearTimeout(h),h=null)},!1);e.forEach(function(a,c){var d=document.createElement("div");d.appendChild(document.createTextNode(a.title));d.dataset.typeIndex=c;d.addEventListener("click",m,!1);a.element=d;b.appendChild(d)});f.parentNode.insertBefore(a,f);b.className="searchdropdown";f.parentNode.insertBefore(b,f);return{getTag:function(){return g.title},setSearchType:function(a){l(e[a])},
getSearch:function(){return g.prefix+f.value},splitTag:function(){var a=f.value.split(n);if(2===a.length){var b=a[0].toLowerCase()+":";var c=a[1];for(a=0;a<e.length;a++)if(b===e[a].prefix){l(e[a]);f.value=c;break}}}}}();d.className="ingredientdropdown";d.appendChild(e);d.addEventListener("mousedown",function(a){a.preventDefault()},!1);(function(){var a=N(m,X.getSearch(),p);d.removeChild(e);e=document.createElement("div");e.dataset.length=0;a.forEach(R,e);d.appendChild(e)})();z.className="clearingredients";
z.appendChild(document.createTextNode("clear"));z.addEventListener("click",function(){if(""===f.value&&"name"===X.getTag())for(;O(n.firstChild);)Q({target:n.firstChild});else f.value="",X.setSearchType(0),Z()},!1);z.addEventListener("mouseover",function(){""===f.value&&"name"===X.getTag()&&(z.firstChild.textContent="clear chosen ingredients")},!1);z.addEventListener("mouseout",function(){"clear"!==z.firstChild.textContent&&(z.firstChild.textContent="clear")},!1);B.className="toggleingredients enabled";
B.addEventListener("click",function(){B.classList.contains("enabled")?(B.classList.remove("enabled"),d.classList.add("hidetext"),B.firstChild.textContent="Show names"):(B.classList.add("enabled"),d.classList.remove("hidetext"),B.firstChild.textContent="Icons only")},!1);B.appendChild(document.createTextNode("Icons only"));n.parentNode.insertBefore(B,n);n.parentNode.insertBefore(z,n);n.parentNode.insertBefore(d,n);f.addEventListener("keydown",function(a){if(-1!==[16,17,37,38,39,40,13].indexOf(a.keyCode)){var b=
w;13===a.keyCode?(null===w&&(w=e.firstChild||null),null!==w&&P({target:w})):null===w?40===a.keyCode&&(w=e.childNodes[1]||e.firstChild||null,null!==w&&(J=w.offsetLeft+w.offsetWidth/2,a.preventDefault())):(a.preventDefault(),37===a.keyCode?(w=w.previousSibling&&w.previousSibling.offsetTop===w.offsetTop?w.previousSibling:(a=K(w,function(a){return a.offsetTop!==w.offsetTop}))?a.previousSibling:e.lastChild,null!==w&&(J=w.offsetLeft+w.offsetWidth/2)):39===a.keyCode?(w=w.nextSibling&&w.nextSibling.offsetTop===
w.offsetTop?w.nextSibling:(a=H(w,function(a){return a.offsetTop!==w.offsetTop}))?a.nextSibling:e.firstChild,null!==w&&(J=w.offsetLeft+w.offsetWidth/2)):38===a.keyCode?((a=H(w,function(a){return J>=a.offsetLeft-1&&J<=a.offsetLeft+a.offsetWidth+1}))||(a=H(e.lastChild,function(a){return J>=a.offsetLeft-1&&J<=a.offsetLeft+a.offsetWidth+1})),w=a?a:e.firstChild):40===a.keyCode&&((a=K(w,function(a){return J>=a.offsetLeft-1&&J<=a.offsetLeft+a.offsetWidth+1}))||(a=K(e.firstChild,function(a){return J>=a.offsetLeft-
1&&J<=a.offsetLeft+a.offsetWidth+1})),w=a?a:e.lastChild));w!==b&&(null!==b&&(b.className=""),null!==w&&(w.className="selected"))}},!1);f.addEventListener("keyup",function(a){-1===[16,17,37,38,39,40,13].indexOf(a.keyCode)?Z():null!==w&&a.preventDefault()},!1);f.addEventListener("focus",function(){I||(I=!0)},!1);f.addEventListener("blur",function(){I&&(I=!1)},!1);v();window.addEventListener("beforeunload",function(){if(window.localStorage){localStorage.foodGuideState||(localStorage.foodGuideState="{}");
var a=JSON.parse(localStorage.foodGuideState);a.pickers||(a.pickers=[]);if(ba){var b=[];b=Array.prototype.map.call(q,function(a){return(a=O(a))?a.id:null});a.pickers[g]=b}else a.pickers[g]=q;localStorage.foodGuideState=JSON.stringify(a)}});Y.push(Z);Y.push(v)})()})();I=function(b){Q(A[b.target.dataset.mode].mask)};F=function(b){Q(E^A[b.target.dataset.mode].bit);b.preventDefault()};var L=document.createElement("li");fa.insertBefore(L,fa.firstChild);L.className="mode";for(var U in A)n=document.createElement("div"),
n.dataset.mode=U,n.addEventListener("click",I,!1),n.addEventListener("contextmenu",F,!1),n.title=A[U].name+"\nleft-click to select\nright-click to toggle",n.className="mode-button",n.appendChild(M("img/"+A[U].img)),L.appendChild(n);Q(E)})();
